### ISSUE TITLE
Can you add Turkish support?

### ISSUE THREAD

**Issue by alitekdemir** [dbrockman/obsidian-change-case#35]
#### Description:
The current case conversion feature can be improved by providing separate shortcuts for Turkish and English text. This allows for a more efficient workflow by not requiring the user to toggle settings when switching between Turkish and English text.

#### Example:

- **Shortcut 1 for English Text:**  
Converts `PMBOK (Project Management Body of Knowledge)` to different cases accurately.

- **Shortcut 2 for Turkish Text:**  
Converts `Proje Yönetimi Bilgi Kitabı` to different cases, taking into account Turkish-specific characters like Ö, Ç, Ş, İ, I, Ğ, Ü.

#### Expected Behavior:

1. Shortcut 1 should handle the English alphabetic characters and provide accurate case conversion.
2. Shortcut 2 should handle both English and Turkish alphabetic characters, especially Turkish-specific ones for accurate case conversion.

#### Suggested Solution:

- Implement two separate shortcuts: one for English text and one for Turkish text.
- Update the case conversion algorithm for the Turkish text shortcut to correctly convert Turkish-specific characters (Ö-ö, Ç-ç, Ş-ş, İ-i, I-ı, Ğ-ğ, Ü-ü).

This would make it easier for users who frequently work with both English and Turkish text, enhancing user experience.

I love chatgpt 😄

**Comment by alitekdemir** [comment]
#### Example:

- **Original Text:**  
`PMBOK (Project Management Body of Knowledge - Proje Yönetimi Bilgi Kitabı)`

- **Lower Cased Text:**  
`pmbok (project management body of knowledge - proje yönetimi bilgi kitabı)`

- **Upper Cased Text:**  
`PMBOK (PROJECT MANAGEMENT BODY OF KNOWLEDGE - PROJE YÖNETIMI BILGI KITABI)`

- **Capital Cased Text:**  
`Pmbok Project Management Body Of Knowledge Proje Y Netimi Bilgi Kitabi`

Some characters are lost.

**Comment by dbrockman** [comment]
Hi @alitekdemir Thanks for the comment!

This plugin is using a different package to do the text transformation called `change-case`. They actually have an open issue about supporting locale-specific text transformation. You can see that issue here: https://github.com/blakeembrey/change-case/issues/297

If that package releases a new version with support for passing in a locale as an option, then I will update this plugin to pass in the current locale used by the system.

I will experiment with splitting words on unicode character category and see if that works better. That might solve the problem with `Yönetimi` being turned into `Y Netimi`.

Some characters will be removed when you use these commands and that is by design. "(", ")", and "-" in the example above gets removed because they are treated as word boundaries. For example, if you select the text "abc-def" and transform to Capital Cased then you will get the text "Abc Def".

**Comment by alitekdemir** [comment]
I am looking forward to it.

**Comment by alitekdemir** [comment]
Wow, the new Turkish feature is working amazingly well! 
I was actually thinking about deleting the plugin because I never thought you guys would tackle this issue. But the dedication you and your team have shown has blown me away. 
You're awesome, well done!

Elinize sağlık.
