### ISSUE TITLE
Possible to run plugin via menu (i.e. not using a hotkey)?

### ISSUE THREAD

**Issue by yurtkuran** [dbrockman/obsidian-change-case#48]
Possible to run plugin via menu (i.e. not using a hotkey)?

**Comment by dbrockman** [comment]
Yes, you can do that.

In the desktop app you can press <kbd>Cmd</kbd> + <kbd>P</kbd> _(mac)_ or <kbd>Ctrl</kbd> + <kbd>P</kbd> _(windows)_ to open the command palette. Then search for the command. Commands added by plugins are always prefixed with the name of the plugin so you can search for _"change case"_ to find all of them.

In the mobile app you can access the commands in two ways:
- pull down from the top of the page to access the command palette. (same as above)
- tap the button in the little toolbar just above the keyboard. It has an icon that looks like this: `Aa`. This button is not added by default because I don't want to assume what people want to do. If you would like to edit the buttons in the toolbar then open _Settings_ and tap _Mobile_, there you can add, remove, and reorder commands in the toolbar.

This plugin adds a command named _"Change Case: Select from list"_ that will show a list of the other commands. This might be helpful to use on mobile.

No hotkeys are added by default. In general I don't think plugins should bind hotkeys by default. It should be up to the user to decide.
